export { WheelGestures as default } from './wheel-gestures/wheel-gestures'
export * from './wheel-gestures/wheel-gestures'
export { configDefaults } from './wheel-gestures/options'
export * from './types'
export * from './utils'
